name: Update VLESS Config

on:
  schedule:
    - cron: '0 */6 * * *' # Автоматический запуск каждые 6 часов
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run Build Script
      run: python build.py

    - name: Commit and Push
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add custom_sub.json
        git commit -m "Авто-обновление конфигов 🇲🇦 🗽 LTE | @telegaproxys" || echo "Изменений нет"
        git push
